### ISSUE TITLE
Confused about how data is stored...

### ISSUE THREAD

**Issue by chrislkeller** [propublica/transcribable#7]
@ashaw: I thought that when I created a transcription, the data was stored not only as an instance of that model , but was written back to record in the "master" table, and that record's verified value was set to true…

That is not what is happening. 
- Am I doing it wrong?
- Is there a verification process that isn't addressed here?
- What does it mean for an record to be verified?

Amazingly though I have it deployed with a user log-in in front of it and am transcribing records. Figured I'd better ask before I got too far.

**EDIT**: I went back and re-read the [blog post](https://www.propublica.org/nerds/item/casino-driven-design) on the Free the Files project and re-read these docs and I now realize I overlooked a couple things when it comes to verification:
- "Each transcription was "verified" after two or more users agreed on all of its data points."
- If you'd like users to be able to transcribe a field, but don't want that field to be verified (for example, interesting notes), add, for example `skip_verification :notes, :related_url`

I have a pretty deep form asking for all things to be verified, when I should probably limit that to fewer fields?

**Comment by ashaw** [comment]
Hey Chris, are you still confused? Yep, I'm pretty sure the data is written back to the master model and marked verified when all data points are agreed upon. The longer the form, the longer it'll take to mark the record as verified (and the more people it will take). I would recommend adding a `skip_verification` to any fields that don't absolutely have to be verified.

**Comment by chrislkeller** [comment]
@ashaw: I think my questions are cleared up on how a record becomes verified, and why no data is being written back to the master table. Gonna close this one down.
